### ISSUE TITLE
Configuration Request file

### ISSUE THREAD

**Issue by sgurin** [alex-oleshkevich/vue-tabler-icons#43]
Hi, is any plans for future configuration of the default options? For example, set stroke-width on all icons in one config file?

Now it is in const variable

![image](https://github.com/alex-oleshkevich/vue-tabler-icons/assets/25930200/f827d47d-e00a-4d35-b91a-4fc9caab0229)

**Comment by alex-oleshkevich** [comment]
Hi, I am in doubt, because library bundle has become very large and continues growing. I tend to think that this library is a bad choice. It may be much better to copy/paste SVG files from https://tabler-icons.io/ and wrap them into your Vue components. A typical project does not use 4k+ icons, and therefore there is no need to download tens of megabytes each time.

**Comment by sgurin** [comment]
For sure, but I use dynamic imports and import only icons that I use in the component. Only one think makes me cry that I cannot configure stroke-width param globally.

**Comment by alex-oleshkevich** [comment]
Then I kindly ask you to submit a PR.
